### ISSUE TITLE
Can we delete this repo?

### ISSUE THREAD

**Issue by rraub** [gios-asu/sustainability-solutions-wordpress-theme#1]
@idmontie Is there anything worth keeping or should we remove this repo?

**Comment by idmontie** [comment]
I think this one is actually being used.

**Comment by rraub** [comment]
On prod they are using the wp-walton theme which isn't this one, nor is the sustainabilitysolutions theme we also have on prod.  I don't see where we are using this theme.

**Comment by idmontie** [comment]
Oh, then sure, let's deprecate it and archive it to common or where ever we
store these things.

On Wed, Aug 5, 2015 at 10:02 AM, Ryan Raub <notifications@github.com> wrote:

> On prod they are using the wp-walton theme which isn't this one, nor is
> the sustainabilitysolutions theme we also have on prod. I don't see where
> we are using this theme.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gios-asu/sustainability-solutions-wordpress-theme/issues/1#issuecomment-128070942>
> .
>



-- 
Best regards,

*Ivan Montiel*
*Web Application Developer*

P.O. Box 875402 | Tempe, Arizona | 85287-5402
Main: 480-965-2975
sustainability.asu.edu

**Comment by rraub** [comment]
done
