### ISSUE TITLE
review changes

### ISSUE THREAD

**Issue by rraub** [gios-asu/sustainability-solutions-wordpress-theme#1]
See if there is anything in here we can add to the base theme.

**Comment by idmontie** [comment]
Some slick slider stuff:
* https://github.com/gios-asu/sustainability-solutions-wordpress-theme/blob/master/stylesheets/scss/_slick.scss
* https://github.com/gios-asu/sustainability-solutions-wordpress-theme/blob/master/javascripts/js/_slick-starter.js

Changes Claire made for the Walton site: https://github.com/gios-asu/sustainability-solutions-wordpress-theme/blob/master/style.css
