### ISSUE TITLE
Is execmasters-page.php used?

### ISSUE THREAD

**Issue by idmontie** [gios-asu/sustainability-solutions-wordpress-theme#3]
We should delete execmasters-page.php if it is not being used. Will most likely need to ask Claire about this.

**Comment by rraub** [comment]
https://sustainabilitysolutions.asu.edu/programs/executivemasters/ does not use that page template, so we can go ahead and remove it.

**Comment by idmontie** [comment]
Where did it come from? Was it added when Claire was working on the theme?

**Comment by rraub** [comment]
it was from the previous version of the theme, (child of wptemplate-gios-v1)
https://github.com/gios-asu/sustainability-solutions-wordpress-theme/blob/master/execmasters-page.php#L14
